version: '3'

services:
    web:
        build:
            context: .
            dockerfile: compose/django/Dockerfile
        container_name: web01
        volumes:
            - .:/src/app
            - ./static:/static
        entrypoint: sh scripts/django/01-init.sh
        ports:
            - 8000:8000
        links:
            - redis
            - rabbit
        env_file:
            - ./.env/.django
            - ./.env/.dbenv
        networks:
            - app-network
        depends_on:
            - database
    worker:
        build:
            context: .
            dockerfile: compose/django/Dockerfile
        command: sh scripts/celery/run_celery.sh
        volumes:
            - .:/src/app
        links:
            - rabbit
            - redis
        depends_on:
            - rabbit
    redis:
        image: redis:latest
        container_name: rd01
        volumes:
            - redis_data:/data
        entrypoint: redis-server --appendonly yes
        ports:
            - 6000:6379
        networks:
            - app-network
    nginx:
        image: nginx:latest
        container_name: nz01
        volumes:
            - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./configs/nginx/snippets:/etc/nginx/snippets
            - ./configs/nginx/cert:/etc/nginx/cert
            - ./static:/app/static
        ports:
            - 8080:80
            - 443:443
        networks:
            - app-network

    database:
        image: postgres:13.1
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
            timeout: 45s
            interval: 10s
            retries: 10
        env_file:
            - ./.env/.dbenv

        logging:
            options:
                max-size: 5m
                max-file: "2"
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - ./scripts/db:/docker-entrypoint-initdb.d/
        ports:
            - 5532:5432
    rabbit:
        image: rabbitmq:latest
        env_file:
            - ./.env/.rabbit
        ports:
            - 15672:15672
            - 5672:5672
        entrypoint: sh rabbit/01-init.sh
        volumes:
            - ./scripts/rabbit:/rabbit
    
networks:
    app-network:
        driver: bridge

volumes:
    local_postgres_data: {}
    redis_data: {}