version: '3.3'

services:
    web:
        build:
            context: .
            dockerfile: compose/django/Dockerfile
        container_name: web01
        volumes:
            - .:/app
        entrypoint: sh scripts/django/01-init.sh
        env_file:
            - ./.env/.django
            - ./.env/.dbenv
        depends_on:
            - database
    celery:
        build:
            context: .
            dockerfile: compose/django/Dockerfile
        command: celery -A system_monitor worker -l INFO
        volumes:
            - .:/app
        depends_on:
            - rabbit
            - redis

    celery-beat:
        build:
            context: .
            dockerfile: compose/django/Dockerfile
        command: celery -A system_monitor beat -l INFO
        volumes:
            - .:/app
        depends_on:
            - celery

    redis:
        image: redis:latest
        container_name: rd01
        volumes:
            - redis_data:/data
        entrypoint: redis-server --appendonly yes

    nginx:
        image: nginx:latest
        container_name: nz01
        volumes:
            - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./configs/nginx/snippets:/etc/nginx/snippets
            - ./configs/nginx/cert:/etc/nginx/cert
            - ./static:/app/static
        ports:
            - 8080:80
            - 443:443
        depends_on:
            - web

    database:
        image: postgres:13.3
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
            timeout: 45s
            interval: 10s
            retries: 10
        env_file:
            - ./.env/.dbenv
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - ./scripts/db:/docker-entrypoint-initdb.d/
    rabbit:
        image: rabbitmq:latest
        env_file:
            - ./.env/.rabbit
        ports:
            - 15672:15672
            - 5672:5672
        entrypoint: sh rabbit/01-init.sh
        volumes:
            - ./scripts/rabbit:/rabbit
volumes:
    local_postgres_data: {}
    redis_data: {}