# Generated by Django 3.2.2 on 2021-05-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('machinename', models.CharField(max_length=100)),
                ('machineid', models.IntegerField()),
                ('machinetype', models.CharField(choices=[('ANY', 'Any'), ('DT', 'Desktop'), ('CS', 'Cloud Server'), ('SBC', 'Single Board')], default='ANY', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cpuutil', models.FloatField()),
                ('cpumem', models.FloatField()),
                ('gpuutil', models.FloatField()),
                ('gpumem', models.FloatField()),
                ('internet_access', models.BooleanField()),
                ('running', models.BooleanField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.machine')),
            ],
        ),
    ]
