# Generated by Django 3.2.2 on 2021-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineinfo',
            name='disk_r',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='disk_w',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='diskspaceleft',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='network_r',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='network_t',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='gpumem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='gpuutil',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='internet_access',
            field=models.BooleanField(null=True),
        ),
    ]
