# Generated by Django 3.2.2 on 2021-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_machine_hasgpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machinename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
