# Generated by Django 3.2.2 on 2021-05-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20210508_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineinfo',
            options={'ordering': ('-created',)},
        ),
    ]
