# Generated by Django 3.2.3 on 2021-05-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('machinename', models.CharField(max_length=100, unique=True)),
                ('machineid', models.IntegerField(unique=True)),
                ('hasgpu', models.BooleanField(default=False)),
                ('machinetype', models.CharField(choices=[('ANY', 'Any'), ('DT', 'Desktop'), ('CS', 'Cloud Server'), ('SBC', 'Single Board')], default='ANY', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cpuutil', models.FloatField()),
                ('cpumem', models.FloatField()),
                ('gpuutil', models.FloatField(null=True)),
                ('gpumem', models.FloatField(null=True)),
                ('diskspaceleft', models.FloatField(null=True)),
                ('disk_r', models.FloatField(null=True)),
                ('disk_w', models.FloatField(null=True)),
                ('network_r', models.FloatField(null=True)),
                ('network_t', models.FloatField(null=True)),
                ('internet_access', models.BooleanField(null=True)),
                ('running', models.BooleanField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_api.machine')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
