# Generated by Django 3.2.3 on 2021-05-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ('-created',)},
        ),
    ]
